### PR TITLE
Add nullability annotations, update dependencies, and clean up

### PR DESCRIPTION
**Pull request by benwicks**

### CODE REVIEW

**Comment by benwicks** [comment]
@parshav Is there documentation for the releasing process for this repo? If not, can you help create a RELEASING.md file to detail that?

**Comment by parshav** [comment]
#12 
Sorry for the day late update, just noticed this and got to it. Thanks for the update on this !
Also, per the releasing md can you change the destination branch to `dev` instead first? I will clean up the branches so we can just do feature -> master instead after.

**Comment by benwicks** [comment]
No worries at all! I changed the destination branch to `dev`.

**Comment by benwicks** [comment]
@parshav Do you think this should constitute a new patch release?

**Comment by parshav** [comment]
Yes to this one. Moving forward, will look to see how we can get a better criteria for each.

**Pull request merged**
